- name: install glpk
  package:
    name: glpk-utils
    state: present

# TODO Clone git repository

- name: Install pip3 dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
    - python3
    - python3-pip
    - python3-setuptools

- name: install python3 project deps
  command: "pip3 install -r /root/cloud-edge-offloading/requirements.txt"
